### ISSUE TITLE
How to use the icons

### ISSUE THREAD

**Issue by uselesswaifu** [CHOK9938/Minecraft_Bedrock-The-Hive-Scoreboard#3]
Sorry for the stupid question, but how do I find out which unicode characters the icons are?

**Comment by uselesswaifu** [comment]
I've figured it out!

**Comment by CHOK9938** [comment]
OK!

ในวันที่ พฤ. 21 ม.ค. 2021 09:56 น. Nora <notifications@github.com> เขียนว่า:
